### ISSUE TITLE
Makoto Title Screen Bug

### ISSUE THREAD

**Issue by MadMax1960** [Pherakki/BlenderToolsForGFS#102] opened 2023-08-20 05:43 UTC
**Describe the bug**
When doing a raw import/export of Makoto's title screen model (c0006_048_00.GMD). The model will not appear on the title screen. 

**To Reproduce**
1. Import c0006_048_00.GMD
2. Export c0006_048_00.GMD with animations packed
3. Boot up game to see if model is there

**Expected behavior**
It should export the model fine, as it does with other models like Joker's 048 and Ryuji's. 

**Files**
c0006_048_00.GMD

**Comment by Pherakki** [comment] 2023-09-05 21:51
Might be related to #95 - will investigate after solving that one

**Comment by Pherakki** [comment] 2023-09-09 22:17
Unrelated to #95, but this happens when merely de-serialising to the GFSInterface class and re-serialising, and so at least one problematic factor is contained entirely in the GFSInterface -> GFSBinary transformation...

**Comment by Pherakki** [comment] 2023-09-09 23:19
The issue is something to do with the packed animations. For some reason, it is sufficient to set the animation node IDs to that of the original model to make the model re-appear (albeit with obviously incorrect animation).
Whether the model is there all along but out of camera, or whether some kind of invalid value is being hit in the IDs is currently unclear.

**Comment by Pherakki** [comment] 2023-09-14 17:29
This is probably going to require the mesh refactor to figure out; will push to v0.2

**Comment by Pherakki** [comment] 2023-09-25 22:20
Fixed in 8de55e21bb14c4b38dfdc6dd16bc286e8476b305

**Closed as completed by Pherakki** 2023-09-25 22:20 UTC
Labels: bug
